-- ============================================================================
-- WARN ELECTRICAL SERVICES, SRL (WES)
-- CARGA INICIAL DE PRODUCTOS EN POSTGRESQL (SEED DATA)
-- ============================================================================

INSERT INTO public.productos (id, codigo, nombre, marca, categoria_id, descripcion, caracteristicas, precio, stock, imagen_url, activo, destacado) VALUES
(
    'prod-001',
    'CAM-IP-4MP-001',
    'Cámara IP Domo 4 MP Ultra HD',
    'Hikvision',
    'camaras',
    'Cámara de videovigilancia domo con resolución 4 MP, visión nocturna EXIR inteligente de hasta 30m y protección IP67 para exterior/interior.',
    '["Resolución 4 Megapíxeles (2560 × 1440)", "Visión nocturna infrarroja EXIR 30 metros", "Compresión eficiente H.265+ para ahorro de almacenamiento", "Protección contra agua y polvo IP67", "Alimentación PoE (802.3af) o 12V DC", "Acceso remoto en tiempo real vía smartphone"]'::jsonb,
    4850.00,
    15,
    'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-002',
    'CAM-BALA-4MP-002',
    'Cámara IP Bala Exterior 4 MP con Audio',
    'Dahua',
    'camaras',
    'Cámara tipo bala para intemperie con lente fijo de 2.8mm, micrófono incorporado de alta sensibilidad y tecnología Smart IR.',
    '["Resolución 4 MP a 30 fps", "Micrófono integrado para audio ambiental", "Alcance nocturno hasta 30m", "Carcasa metálica antivandálica con norma IP67", "Detección inteligente de movimiento con filtrado humano"]'::jsonb,
    5200.00,
    20,
    'https://images.unsplash.com/photo-1549100156-427908b98e1f?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-003',
    'CAM-PTZ-WIFI-003',
    'Cámara PTZ WiFi 360° Exterior con Seguimiento',
    'EZVIZ / WES',
    'camaras',
    'Cámara motorizada con giro horizontal de 352° y vertical de 95°, seguimiento automático de objetivos y foco luminoso de disuasión.',
    '["Visión panorámica 360° motorizada", "Resolución 2K (3 Megapíxeles)", "Visión nocturna a todo color mediante reflectores LED", "Audio bidireccional (altavoz y micrófono)", "Sirena y luz estroboscópica disuasoria integrada", "Conexión WiFi de doble antena de largo alcance"]'::jsonb,
    6900.00,
    8,
    'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-004',
    'NVR-4K-08P-001',
    'Grabador de Video NVR 8 Canales 4K PoE',
    'Hikvision',
    'grabadores',
    'Grabador de red para 8 cámaras IP con puertos PoE independientes Plug & Play, soporte para discos de hasta 10TB y salida HDMI 4K.',
    '["8 puertos PoE integrados para conexión directa de cámaras", "Soporte de cámaras de hasta 8 MP (4K)", "Decodificación y compresión H.265+", "Salidas simultáneas HDMI 4K y VGA", "Configuración rápida P2P para visualización en celular", "Alertas push instantáneas de eventos"]'::jsonb,
    13500.00,
    5,
    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-005',
    'DVR-16CH-HD-002',
    'Grabador DVR 16 Canales Pentahíbrido',
    'Dahua',
    'grabadores',
    'Grabador digital pentahíbrido compatible con tecnologías HDCVI, AHD, TVI, CVBS e IP, ideal para modernización de sistemas existentes.',
    '["16 canales analógicos HD + canales IP adicionales", "Transmisión a larga distancia por cable coaxial o UTP", "Búsqueda inteligente por área de detección", "Ventilador de bajo ruido y diseño térmico optimizado"]'::jsonb,
    11200.00,
    4,
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
    TRUE,
    FALSE
),
(
    'prod-006',
    'BIO-FACIAL-F100',
    'Terminal Biométrico de Acceso Facial y Huella',
    'ZKTeco',
    'acceso',
    'Control de acceso y asistencia con reconocimiento facial Visible Light anti-suplantación, lector de huellas digitales SilkID y tarjetas RFID.',
    '["Capacidad para 3,000 rostros y 3,000 huellas", "Reconocimiento ultrarrápido en menos de 0.3 segundos", "Pantalla táctil IPS de 5 pulgadas", "Conectividad TCP/IP, WiFi y USB", "Relé para control de cerradura electromagnética o pestillo"]'::jsonb,
    18900.00,
    6,
    'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-007',
    'ACC-KEY-RFID-007',
    'Teclado Autónomo RFID Metálico Exterior',
    'WES Pro',
    'acceso',
    'Control de acceso para puerta individual con teclado retroiluminado antivandálico y lector de llaveros/tarjetas de proximidad 125 kHz.',
    '["Estructura metálica de alta resistencia con norma IP68", "Apertura por PIN numérico, tarjeta RFID o PIN + Tarjeta", "Capacidad para hasta 2,000 usuarios", "Salida de relé temporizada programable"]'::jsonb,
    3600.00,
    25,
    'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    TRUE,
    FALSE
),
(
    'prod-008',
    'LOCK-SMART-WF-008',
    'Cerradura Inteligente WiFi con Huella y Teclado',
    'Tuya / Smart WES',
    'cerraduras',
    'Cerradura digital de sobreponer o embutir con 5 métodos de apertura: huella biométrica, código digital, tarjeta IC, llave mecánica y app móvil.',
    '["Apertura remota desde smartphone en cualquier lugar", "Generación de contraseñas temporales para visitas o personal", "Registro de accesos en tiempo real con fecha y hora", "Alarma de intento de intrusión y batería baja", "Alimentación con baterías AA de hasta 12 meses de duración"]'::jsonb,
    9800.00,
    10,
    'https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-009',
    'MAG-LOCK-600-ZL',
    'Cerradura Electromagnética de 600 Lbs con Soporte ZL',
    'Securitron / WES',
    'cerraduras',
    'Electroimán para puertas de madera, metal o vidrio con fuerza de retención de 600 libras (280 kg), sensor de estado LED y soporte multiposición.',
    '["Fuerza de retención magnética de 280 kg / 600 lbs", "Voltaje dual 12V / 24V DC con bajo consumo", "Diseño anti-magnetismo residual", "Incluye soporte tipo ZL para montaje flexible", "Indicador visual de estado de bloqueo (LED verde/rojo)"]'::jsonb,
    4950.00,
    18,
    'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80',
    TRUE,
    FALSE
),
(
    'prod-010',
    'INTER-IP-7IN-010',
    'Videoportero IP WiFi con Pantalla Táctil 7"',
    'Hikvision',
    'intercom',
    'Sistema completo de intercomunicación con placa exterior de cámara Full HD gran angular y monitor táctil de interior con recepción en el celular.',
    '["Placa de calle con cámara 1080p y visión nocturna", "Monitor de 7 pulgadas táctil a color para pared", "Atención y apertura de puerta remota desde el celular", "Grabación de mensajes y captura de fotos de visitantes", "Alimentación estándar PoE"]'::jsonb,
    16500.00,
    7,
    'https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-011',
    'ALM-KIT-WF-011',
    'Panel de Alarma Inalámbrico WiFi/GSM Kit Completo',
    'Tuya Smart / WES',
    'alarmas',
    'Kit de seguridad inteligente que incluye central inalámbrica, sensor de movimiento PIR, contacto magnético para puerta/ventana y 2 controles remotos.',
    '["Doble vía de comunicación: WiFi residencial e inserción de SIM GSM", "Sirena interna integrada de 90 dB + soporte para sirena exterior", "Notificaciones instantáneas vía App y llamada telefónica o SMS", "Batería recargable de respaldo ante cortes eléctricos de hasta 8 horas", "Compatible con asistentes Google Home y Alexa"]'::jsonb,
    7400.00,
    12,
    'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
),
(
    'prod-012',
    'NET-SW-8P-GB',
    'Switch PoE Gigabit 8 Puertos + 2 Uplink',
    'Ubiquiti / TP-Link',
    'redes',
    'Switch administrado de 8 puertos PoE+ 10/100/1000 Mbps con potencia total de 120W y 2 puertos Gigabit adicionales para enlace con router.',
    '["8 puertos compatibles con estándares IEEE 802.3af/at", "Potencia total de suministro PoE hasta 120W", "Función Extend de hasta 250 metros para cámaras lejanas", "Prioridad de puertos QoS y aislamiento VLAN automático", "Chasis metálico resistente con montaje en rack o pared"]'::jsonb,
    6800.00,
    9,
    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    TRUE,
    FALSE
),
(
    'prod-013',
    'PWR-BOX-12V10A-9',
    'Fuente de Poder Centralizada 12V 10A (9 Salidas)',
    'WES Power',
    'energia',
    'Caja de distribución de energía regulada con 9 salidas protegidas por fusibles PTC auto-recuperables e indicador LED individual.',
    '["Entrada 110V/220V AC conmutada", "Salida estabilizada 12V DC total 10 Amperios", "9 terminales de salida con fusibles térmicos PTC independientes", "Gabinete metálico con cerradura de seguridad con llave", "Espacio para batería de respaldo opcional"]'::jsonb,
    2950.00,
    30,
    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    TRUE,
    FALSE
),
(
    'prod-014',
    'CAB-CAT6-EXT-305',
    'Bobina Cable UTP Cat6 100% Cobre Exterior 305m',
    'Panduit / Furukawa',
    'cables',
    'Cable de red estructurado categoría 6 certificado para exteriores con doble chaqueta UV e hilo de desgarre para instalaciones de CCTV y redes.',
    '["Conductores 100% cobre sólido 23 AWG", "Doble recubrimiento PE resistente a rayos ultravioleta y humedad", "Ancho de banda testeado de hasta 250 MHz", "Longitud en caja dispensadora de 305 metros (1,000 pies)", "Ideal para tendidos a la intemperie y ducterías"]'::jsonb,
    8900.00,
    14,
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    TRUE,
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    precio = EXCLUDED.precio,
    stock = EXCLUDED.stock,
    imagen_url = EXCLUDED.imagen_url,
    descripcion = EXCLUDED.descripcion;
